package com.bdscontrol.app;

import java.io.*;import java.nio.file.Path;import java.util.*;import java.util.zip.*;import org.apache.commons.compress.archivers.tar.*;import org.apache.commons.compress.compressors.xz.XZCompressorInputStream;

final class ArchiveExtractor {
 static void zip(File archive,File dest)throws Exception{dest.mkdirs();try(ZipInputStream in=new ZipInputStream(new FileInputStream(archive))){ZipEntry e;byte[]b=new byte[65536];while((e=in.getNextEntry())!=null){File f=safe(dest,e.getName());if(e.isDirectory())f.mkdirs();else{f.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(f)){int n;while((n=in.read(b))>0)o.write(b,0,n);}}}}}
 static void tarGz(File archive,File dest)throws Exception{try(InputStream in=new GZIPInputStream(new BufferedInputStream(new FileInputStream(archive)))){tar(in,dest);}}
 static void tarXz(File archive,File dest)throws Exception{try(InputStream in=new XZCompressorInputStream(new BufferedInputStream(new FileInputStream(archive)))){tar(in,dest);}}
 private static File safe(File d,String n)throws IOException{File f=new File(d,n);if(!f.toPath().normalize().startsWith(d.toPath().normalize()))throw new SecurityException("unsafe archive path");return f;}
 private static void tar(InputStream in,File dest)throws Exception{
  dest.mkdirs();List<String[]> symlinks=new ArrayList<>(),hardlinks=new ArrayList<>();
  try(TarArchiveInputStream t=new TarArchiveInputStream(in)){TarArchiveEntry e;byte[]b=new byte[65536];while((e=t.getNextTarEntry())!=null){File f=safe(dest,e.getName());if(e.isDirectory()){f.mkdirs();continue;}if(e.isSymbolicLink()){symlinks.add(new String[]{e.getName(),e.getLinkName()});continue;}if(e.isLink()){hardlinks.add(new String[]{e.getName(),e.getLinkName()});continue;}f.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(f)){int n;while((n=t.read(b))>0)o.write(b,0,n);}}}
  for(String[] l:hardlinks){File f=safe(dest,l[0]),target=findTarget(dest,safeLinkTarget(dest,f,l[1]));f.getParentFile().mkdirs();f.delete();try{android.system.Os.link(target.getAbsolutePath(),f.getAbsolutePath());}catch(Throwable ignored){copy(target,f);}if(!f.isFile())throw new IOException("Не удалось воссоздать hardlink "+l[0]+" -> "+l[1]);}
  for(String[] l:symlinks){File f=safe(dest,l[0]);File target=safeLinkTarget(dest,f,l[1]);if(!target.isFile())target=findTarget(dest,target);f.getParentFile().mkdirs();f.delete();if(!target.isFile())throw new IOException("Не найден target guest-библиотеки "+l[0]+" -> "+l[1]);try{Path parent=f.getParentFile().toPath().toAbsolutePath().normalize();Path targetPath=target.toPath().toAbsolutePath().normalize();android.system.Os.symlink(parent.relativize(targetPath).toString(),f.getAbsolutePath());}catch(Throwable ignored){copy(target,f);}if(!f.isFile())throw new IOException("Сломанная guest-ссылка "+l[0]+" -> "+l[1]);}
 }
 private static File safeLinkTarget(File dest,File link,String name)throws IOException{File target;if(name.startsWith("/"))target=new File(dest,name.substring(1));else if(name.startsWith("./"))target=new File(dest,name.substring(2));else target=new File(link.getParentFile(),name);File normalized=target.getCanonicalFile();if(!normalized.toPath().startsWith(dest.getCanonicalFile().toPath()))throw new SecurityException("unsafe link target");return normalized;}
 private static File findTarget(File dest,File wanted){String name=wanted.getName();ArrayDeque<File> q=new ArrayDeque<>();q.add(dest);while(!q.isEmpty()){File d=q.remove();File[] fs=d.listFiles();if(fs==null)continue;for(File f:fs){if(f.isFile()&&f.getName().equals(name))return f;if(f.isDirectory())q.add(f);}}return wanted;}
 private static void copy(File from,File to)throws IOException{if(!from.isFile())return;try(InputStream i=new FileInputStream(from);OutputStream o=new FileOutputStream(to)){byte[]b=new byte[65536];int n;while((n=i.read(b))>0)o.write(b,0,n);}}
}
