package com.bdscontrol.app;

import java.io.*;import java.nio.charset.StandardCharsets;import java.util.LinkedHashMap;import java.util.Map;

final class PropertiesManager {
    static void writeDefaults(File file,String levelName,String port)throws IOException{
        Map<String,String> p=new LinkedHashMap<>();
        p.put("server-name","Bedrock level");p.put("gamemode","survival");p.put("force-gamemode","false");p.put("difficulty","easy");p.put("allow-cheats","false");p.put("max-players","10");p.put("online-mode","true");p.put("allow-list","false");p.put("server-port",port==null||port.isEmpty()?"19132":port);p.put("server-portv6","19133");p.put("view-distance","10");p.put("tick-distance","4");p.put("player-idle-timeout","30");p.put("level-name",levelName==null||levelName.isEmpty()?"Bedrock level":levelName);p.put("level-seed","");p.put("default-player-permission-level","member");
        file.getParentFile().mkdirs();try(Writer w=new OutputStreamWriter(new FileOutputStream(file),StandardCharsets.UTF_8)){w.write("# Generated by BDS Control\n");for(Map.Entry<String,String> e:p.entrySet())w.write(e.getKey()+"="+e.getValue()+"\n");}
    }
}
