package com.bdscontrol.app;

import android.content.Context;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.TimeUnit;

final class RuntimeManager {
 private static final String[] REQUIRED={"libc.so.6","libm.so.6","libpthread.so.0","libdl.so.2","librt.so.1","libgcc_s.so.1","libstdc++.so.6","ld-linux-x86-64.so.2"};
 private final Context context;private final File root,x86Libs,bin;
 RuntimeManager(Context c){context=c.getApplicationContext();root=new File(c.getFilesDir(),"bds-runtime");x86Libs=new File(root,"x86lib");bin=new File(root,"bin");root.mkdirs();}
 File root(){return root;}File x86Libs(){return x86Libs;}File bin(){return bin;}File serverDir(){return new File(root,"server");}
 File box64(){return new File(context.getApplicationInfo().nativeLibraryDir,"libbox64.so");}
 boolean box64Present(){File b=box64();return b.isFile()&&(b.canExecute()||b.setExecutable(true,false));}
 boolean guestLibsPresent(){return missingGuestLibraries().isEmpty();}boolean ready(){return box64Present()&&guestLibsPresent();}
 String guestLibPath(File server){LinkedHashSet<String> dirs=new LinkedHashSet<>();if(server!=null)dirs.add(server.getAbsolutePath());dirs.add(x86Libs.getAbsolutePath());collectDirs(x86Libs,dirs);StringBuilder s=new StringBuilder();for(String d:dirs){if(s.length()>0)s.append(':');s.append(d);}return s.toString();}
 private void collectDirs(File d,Set<String> out){if(d==null||!d.isDirectory())return;File[] fs=d.listFiles();if(fs==null)return;boolean has=false;for(File f:fs)if(f.isFile()&&f.length()>0)has=true;if(has)out.add(d.getAbsolutePath());for(File f:fs)if(f.isDirectory())collectDirs(f,out);}
 private void collectFiles(File d,List<File> out){if(d==null||!d.isDirectory())return;File[] fs=d.listFiles();if(fs==null)return;for(File f:fs){if(f.isFile()&&f.length()>0)out.add(f);if(f.isDirectory())collectFiles(f,out);}}
 private File find(String name){List<File> files=new ArrayList<>();collectFiles(x86Libs,files);for(File f:files)if(f.getName().equals(name))return f;return null;}
 List<String> missingGuestLibraries(){List<String> missing=new ArrayList<>();for(String n:REQUIRED)if(find(n)==null)missing.add(n);return missing;}
 String libraryReport(){List<File> files=new ArrayList<>();collectFiles(x86Libs,files);files.sort(Comparator.comparing(File::getAbsolutePath));StringBuilder s=new StringBuilder("Guest library root: ").append(x86Libs.getAbsolutePath()).append("\nBOX64_LD_LIBRARY_PATH: ").append(guestLibPath(serverDir())).append("\nFound ").append(files.size()).append(" guest library files:\n");for(File f:files)s.append("- ").append(f.getAbsolutePath()).append(" size=").append(f.length()).append("\n");List<String> miss=missingGuestLibraries();if(!miss.isEmpty())s.append("MISSING REQUIRED: ").append(miss).append("\n");return s.toString();}
 Map<String,String> env(File work){File tmp=new File(context.getCacheDir(),"tmp");tmp.mkdirs();String nd=context.getApplicationInfo().nativeLibraryDir;Map<String,String> e=new HashMap<>();e.put("HOME",work.getAbsolutePath());e.put("TMPDIR",tmp.getAbsolutePath());e.put("PATH",nd+":"+work.getAbsolutePath());e.put("LD_LIBRARY_PATH",nd);e.put("BOX64_LD_LIBRARY_PATH",guestLibPath(work));e.put("BOX64_PATH",work.getAbsolutePath());e.put("BOX64_DYNAREC","1");e.put("BOX64_LOG","1");e.put("BOX64_NOBANNER","0");e.put("BOX64_PREFER_EMULATED","1");e.put("BOX64_EMULATED_LIBS","libc.so.6:libpthread.so.0:libdl.so.2:libm.so.6:libgcc_s.so.1:libstdc++.so.6:libbsd.so.0:ld-linux-x86-64.so.2");e.put("BOX64_SHOWSEGV","1");e.put("BOX64_SHOWBT","1");return e;}
 String selfTest(){File b=box64();if(!b.isFile())return "файла нет: "+b.getAbsolutePath();if(!b.canExecute()&&!b.setExecutable(true,false))return "нет права на запуск: "+b.getAbsolutePath();Process p=null;try{ProcessBuilder pb=new ProcessBuilder(b.getAbsolutePath());pb.redirectErrorStream(true);pb.environment().put("BOX64_VERSION","1");p=pb.start();StringBuilder out=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()))){String l;while((l=r.readLine())!=null&&out.length()<600)out.append(l).append(" | ");}if(!p.waitFor(15,TimeUnit.SECONDS)){p.destroy();return "не ответил за 15 секунд: "+out;}String t=out.toString().trim();return t.isEmpty()?"код выхода "+p.exitValue():t;}catch(Exception e){if(p!=null)p.destroy();return "не запускается: "+e;}}
 String reason(){if(!box64Present())return "Box64 не найден или не исполняем: "+box64().getAbsolutePath()+"; nativeLibraryDir="+context.getApplicationInfo().nativeLibraryDir;List<String> miss=missingGuestLibraries();if(!miss.isEmpty())return "Отсутствуют guest-библиотеки: "+miss;return "Runtime готов";}
 String status(){try{JSONObject o=new JSONObject();o.put("mode","box64-direct");o.put("ready",ready());o.put("box64Present",box64Present());o.put("box64",box64().getAbsolutePath());o.put("nativeLibraryDir",context.getApplicationInfo().nativeLibraryDir);o.put("guestLibRoot",x86Libs.getAbsolutePath());o.put("guestLibDirs",new JSONArray(guestLibPath(serverDir()).split(":")));o.put("missingGuestLibraries",new JSONArray(missingGuestLibraries()));o.put("server",serverDir().getAbsolutePath());o.put("proot",false);o.put("rootfs",false);o.put("reason",reason());return o.toString();}catch(Exception e){return "{\"ready\":false}";}}
}
