package com.bdscontrol.app;

import android.content.Context;import org.json.JSONArray;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.zip.*;

final class RuntimeBootstrap {
 interface Events{void message(String type,String text);void progress(long done,long total);}
 private final File root;private final Events events;
 RuntimeBootstrap(Context c,Events e){root=new File(c.getFilesDir(),"bds-runtime/runtime");events=e;root.mkdirs();}
 boolean ready(){return executable("bin/proot")&&executable("bin/box64")&&new File(root,"rootfs/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2").isFile();}
 void ensure(){new Thread(()->{try{if(!executable("bin/proot"))downloadProot();if(!executable("bin/box64"))downloadBox64();if(!new File(root,"rootfs/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2").isFile())downloadRootfs();if(!ready())throw new IOException("runtime incomplete after bootstrap");events.message("ready","Embedded PRoot, Box64 and glibc rootfs are ready");}catch(Exception e){events.message("error","Runtime bootstrap failed: "+e.getMessage());}},"runtime-bootstrap").start();}
 private boolean executable(String rel){File f=new File(root,rel);return f.isFile()&&f.setExecutable(true,false);}
 private void downloadProot()throws Exception{File out=new File(root,"bin/proot");out.getParentFile().mkdirs();download("https://raw.githubusercontent.com/proot-me/proot-static-build/master/static/proot-arm64",out,null);if(!executable("bin/proot"))throw new IOException("cannot make PRoot executable");events.message("info","Downloaded PRoot arm64");}
 private void downloadBox64()throws Exception{String url=releaseAsset("ptitSeb","box64",new String[]{"arm64","aarch64"});if(url==null)throw new IOException("Box64 release has no downloadable ARM64 asset; source builds cannot be performed safely inside APK");File out=new File(root,"bin/box64");download(url,out,null);if(!executable("bin/box64"))throw new IOException("cannot make Box64 executable");events.message("info","Downloaded Box64 ARM64 release asset");}
 private void downloadRootfs()throws Exception{String url=releaseAsset("termux","proot-distro",new String[]{"debian","aarch64"});if(url==null)throw new IOException("No Debian ARM64 rootfs asset found");File archive=new File(root,"debian-rootfs");download(url,archive,null);extractTar(archive,new File(root,"rootfs"));archive.delete();events.message("info","Downloaded and extracted Debian ARM64 rootfs");}
 private String releaseAsset(String owner,String repo,String[] alternatives)throws Exception{String json=http("https://api.github.com/repos/"+owner+"/"+repo+"/releases/latest");JSONArray a=new JSONObject(json).optJSONArray("assets");if(a==null)return null;for(int i=0;i<a.length();i++){String n=a.getJSONObject(i).optString("name").toLowerCase(Locale.US);for(String term:alternatives)if(n.contains(term.toLowerCase(Locale.US))&&!n.endsWith(".sha256"))return a.getJSONObject(i).optString("browser_download_url",null);}return null;}
 private String http(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestProperty("Accept","application/vnd.github+json");c.setRequestProperty("User-Agent","BDS-Control/0.1");try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[]b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);return out.toString(StandardCharsets.UTF_8.name());}}
 private void download(String url,File out,DownloadManager.Progress p)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestProperty("User-Agent","BDS-Control/0.1");c.connect();if(c.getResponseCode()/100!=2)throw new IOException("HTTP "+c.getResponseCode()+" for "+url);long total=c.getContentLengthLong(),done=0;out.getParentFile().mkdirs();try(InputStream in=c.getInputStream();OutputStream os=new FileOutputStream(out)){byte[]b=new byte[65536];int n;while((n=in.read(b))>0){os.write(b,0,n);done+=n;if(p!=null)p.update(done,total);events.progress(done,total);}}}
 private void extractTar(File archive,File dest)throws Exception{InputStream raw=new FileInputStream(archive);if(archive.getName().endsWith(".gz"))raw=new GZIPInputStream(raw);try(InputStream in=raw){tar(in,dest);}}
 private void tar(InputStream in,File dest)throws Exception{byte[]h=new byte[512],buf=new byte[65536];while(true){int got=readFully(in,h);if(got<512||empty(h))break;String name=text(h,0,100);long size=oct(h,124,12);int type=h[156];File f=new File(dest,name);if(!f.toPath().normalize().startsWith(dest.toPath().normalize()))throw new SecurityException("unsafe tar path");if(type=='5'){f.mkdirs();}else{f.getParentFile().mkdirs();try(OutputStream out=new FileOutputStream(f)){long left=size;while(left>0){int n=in.read(buf,0,(int)Math.min(buf.length,left));if(n<0)throw new EOFException();out.write(buf,0,n);left-=n;}}}long skip=(512-(size%512))%512;while(skip>0){long n=in.skip(skip);if(n<=0)break;skip-=n;}}}
 private static int readFully(InputStream in,byte[]b)throws IOException{int p=0,n;while(p<b.length&&(n=in.read(b,p,b.length-p))>0)p+=n;return p;}private static boolean empty(byte[]b){for(byte x:b)if(x!=0)return false;return true;}private static String text(byte[]b,int p,int n){int e=p;while(e<p+n&&b[e]!=0)e++;return new String(b,p,e-p,StandardCharsets.UTF_8).trim();}private static long oct(byte[]b,int p,int n){String s=text(b,p,n).trim();return s.isEmpty()?0:Long.parseLong(s,8);}
}
