package com.bdscontrol.app;

import android.content.Context;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.TimeUnit;

final class RuntimeManager {
 private static final String[] REQUIRED=RuntimeInstaller.REQUIRED;
 private final Context context;private final File root,x86Libs,guestLibs,bin;
 RuntimeManager(Context c){context=c.getApplicationContext();root=new File(c.getFilesDir(),"bds-runtime");x86Libs=new File(root,"x86lib");guestLibs=new File(root,"guest-libs");bin=new File(root,"bin");root.mkdirs();}
 File root(){return root;}File x86Libs(){return x86Libs;}File bin(){return bin;}File serverDir(){return new File(root,"server");}
 File box64(){return new File(context.getApplicationInfo().nativeLibraryDir,"libbox64.so");}
 boolean box64Present(){File b=box64();return b.isFile()&&(b.canExecute()||b.setExecutable(true,false));}
 private File find(String name){File f=new File(guestLibs,name);return f.isFile()&&f.length()>0?f:null;}
 List<String> missingGuestLibraries(){List<String> m=new ArrayList<>();for(String n:REQUIRED)if(find(n)==null)m.add(n);return m;}
 boolean guestLibsPresent(){return missingGuestLibraries().isEmpty();}boolean ready(){return box64Present()&&guestLibsPresent();}
 String guestLibPath(File server){LinkedHashSet<String> d=new LinkedHashSet<>();d.add(guestLibs.getAbsolutePath());d.add(x86Libs.getAbsolutePath());if(server!=null)d.add(server.getAbsolutePath());return String.join(":",d);}
 String libraryReport(){StringBuilder s=new StringBuilder("Official Box64 bundle contract: glibc/libc/libpthread/libdl/libm/librt/ld-linux are intentionally omitted and provided by Box64.\nGuest runtime root: ").append(root).append("\nGuest library directory: ").append(guestLibs).append("\nBOX64_LD_LIBRARY_PATH: ").append(guestLibPath(serverDir())).append("\n");for(String n:REQUIRED)s.append(find(n)!=null?"FOUND ":"MISSING ").append(n).append("\n");return s.toString();}
 Map<String,String> env(File work){File tmp=new File(context.getCacheDir(),"tmp");tmp.mkdirs();String nd=context.getApplicationInfo().nativeLibraryDir;Map<String,String> e=new HashMap<>();e.put("HOME",work.getAbsolutePath());e.put("TMPDIR",tmp.getAbsolutePath());e.put("PATH",nd+":"+work.getAbsolutePath());e.put("LD_LIBRARY_PATH",nd);e.put("BOX64_LD_LIBRARY_PATH",guestLibPath(work));e.put("BOX64_PATH",work.getAbsolutePath());e.put("BOX64_DYNAREC","1");e.put("BOX64_LOG","1");e.put("BOX64_NOBANNER","0");e.put("BOX64_PREFER_EMULATED","1");e.put("BOX64_EMULATED_LIBS","libc.so.6:libpthread.so.0:libdl.so.2:libm.so.6:libgcc_s.so.1:libstdc++.so.6:libbsd.so.0:ld-linux-x86-64.so.2");e.put("BOX64_SHOWSEGV","1");e.put("BOX64_SHOWBT","1");return e;}
 String selfTest(){File b=box64();if(!b.isFile())return "файла нет: "+b.getAbsolutePath();if(!b.canExecute()&&!b.setExecutable(true,false))return "нет права на запуск: "+b.getAbsolutePath();Process p=null;try{ProcessBuilder pb=new ProcessBuilder(b.getAbsolutePath());pb.redirectErrorStream(true);pb.environment().put("BOX64_VERSION","1");p=pb.start();StringBuilder out=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()))){String l;while((l=r.readLine())!=null&&out.length()<600)out.append(l).append(" | ");}if(!p.waitFor(15,TimeUnit.SECONDS)){p.destroy();return "не ответил за 15 секунд: "+out;}String t=out.toString().trim();return t.isEmpty()?"код выхода "+p.exitValue():t;}catch(Exception e){if(p!=null)p.destroy();return "не запускается: "+e;}}
 String reason(){if(!box64Present())return "Box64 не найден или не исполняем: "+box64().getAbsolutePath()+"; nativeLibraryDir="+context.getApplicationInfo().nativeLibraryDir;List<String> m=missingGuestLibraries();return m.isEmpty()?"Runtime готов":"Отсутствуют supplemental guest-библиотеки: "+m;}
 String status(){try{return new JSONObject().put("mode","box64-direct").put("ready",ready()).put("box64Present",box64Present()).put("box64",box64().getAbsolutePath()).put("nativeLibraryDir",context.getApplicationInfo().nativeLibraryDir).put("guestLibRoot",guestLibs.getAbsolutePath()).put("guestLibDirs",new JSONArray(guestLibPath(serverDir()).split(":"))).put("missingGuestLibraries",new JSONArray(missingGuestLibraries())).put("server",serverDir().getAbsolutePath()).put("proot",false).put("rootfs",false).put("reason",reason()).toString();}catch(Exception e){return "{\"ready\":false}";}}
}
