package com.bdscontrol.app;

import android.content.Context;import android.content.Intent;import android.os.Build;import org.json.JSONObject;import java.io.*;import java.util.*;import java.util.zip.*;

public final class ServerManager {
 private final MainActivity a; private final Context context; private final File root; private final ProcessManager pm=new ProcessManager(); private final LogManager logs; private final PlayitManager playit; private final RuntimeManager runtime; private final AppConfig config; private final MonitorManager monitor; private volatile String state="stopped",version=""; private long started; private volatile boolean shuttingDown;
 public ServerManager(Context c){context=c;a=(MainActivity)c;root=new File(c.getFilesDir(),"bds-runtime");root.mkdirs();logs=new LogManager(a);playit=new PlayitManager(logs);runtime=new RuntimeManager(c);config=new AppConfig(c);monitor=new MonitorManager(c);version=config.get("version","");}
 void configure(String json){config.put("config",json==null?"{}":json);logs.event("info","Configuration saved locally");}
 void install(String v,String expected){version=v;config.put("version",v);new Thread(()->{try{state="installing";emitState();File zip=new File(root,"bds.zip");String url="https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-"+v+".zip";DownloadManager.download(url,zip,(d,t)->progress(d,t));String hash=DownloadManager.sha256(zip);if(expected!=null&&!expected.isEmpty()&&!hash.equalsIgnoreCase(expected))throw new SecurityException("SHA-256 mismatch: "+hash);File server=new File(root,"server");unzip(zip,server);File props=new File(server,"server.properties");if(!props.exists())PropertiesManager.writeDefaults(props,"Bedrock level","19132");logs.event("ready","BDS downloaded, extracted and configured; SHA-256="+hash);state="stopped";emitState();}catch(Exception e){state="error";logs.event("error",e.toString());emitState();}},"bds-install").start();}
 private void progress(long d,long t){try{JSONObject o=new JSONObject();o.put("done",d);o.put("total",t);a.emit("progress",o.toString());}catch(Exception ignored){}}
 private void unzip(File z,File to)throws Exception{to.mkdirs();try(ZipInputStream in=new ZipInputStream(new FileInputStream(z))){ZipEntry e;byte[]b=new byte[65536];while((e=in.getNextEntry())!=null){File f=new File(to,e.getName());if(!f.toPath().normalize().startsWith(to.toPath().normalize()))throw new SecurityException("unsafe zip path");if(e.isDirectory())f.mkdirs();else{f.getParentFile().mkdirs();try(OutputStream o=new FileOutputStream(f)){int n;while((n=in.read(b))>0)o.write(b,0,n);}}}}}
 void start(){shuttingDown=false;new Thread(()->{try{File dir=new File(root,"server");File bin=new File(dir,"bedrock_server");if(!bin.exists())throw new FileNotFoundException("bedrock_server not installed");if(!runtime.ready())throw new IllegalStateException("Official BDS is x86_64. Embedded Box64 + x86_64 glibc runtime is missing or incomplete.");Intent service=new Intent(context,ServerService.class);if(Build.VERSION.SDK_INT>=26)context.startForegroundService(service);else context.startService(service);Map<String,String> env=new HashMap<>();env.put("LD_LIBRARY_PATH",new File(root,"runtime/lib/x86_64-linux-gnu").getAbsolutePath());List<String> cmd=Arrays.asList(runtime.box64().getAbsolutePath(),bin.getAbsolutePath());state="starting";emitState();pm.start(cmd,dir,env,(src,line)->logs.line(src,line));started=System.currentTimeMillis();state="running";emitState();watch();}catch(Exception e){state="error";logs.event("error",e.toString());emitState();}},"bds-start").start();}
 private void watch(){new Thread(()->{try{while(pm.alive()&&!shuttingDown)Thread.sleep(1000);if(!shuttingDown){state="error";logs.event("error","BDS process exited unexpectedly; no automatic restart was attempted");emitState();}}catch(InterruptedException ignored){}},"bds-watchdog").start();}
 void stop(){shuttingDown=true;pm.stop();context.stopService(new Intent(context,ServerService.class));state="stopped";emitState();} void restart(){stop();try{Thread.sleep(250);}catch(Exception ignored){}start();} void stopAll(){shuttingDown=true;pm.stop();context.stopService(new Intent(context,ServerService.class));}
 void sendCommand(String c){try{pm.write(c);}catch(Exception e){logs.event("error","stdin: "+e);}}
 String systemJson(){return monitor.snapshot();}
 String statusJson(){try{JSONObject o=new JSONObject();o.put("state",state);o.put("version",version);o.put("alive",pm.alive());o.put("startedAt",started);o.put("runtime",new JSONObject(runtime.status()));return o.toString();}catch(Exception e){return "{}";}}
 private void emitState(){a.emit("state",statusJson());}
}
