package com.bdscontrol.app;

import android.content.*;import android.net.Uri;import android.os.Build;import org.json.*;import java.io.*;import java.net.*;import java.util.*;

public final class ServerManager {
 private final MainActivity a;private final Context context;private final File root;private final ProcessManager pm=new ProcessManager();private final LogManager logs;private final RuntimeManager runtime;private final AppConfig config;private final MonitorManager monitor;private final PlayitManager playit;private volatile String state="stopped",version="";private long started;private volatile boolean shuttingDown;private int restarts;
 public ServerManager(Context c){context=c;a=(MainActivity)c;root=new File(c.getFilesDir(),"bds-runtime");root.mkdirs();logs=new LogManager(a);runtime=new RuntimeManager(c);config=new AppConfig(c);monitor=new MonitorManager(c);playit=new PlayitManager(c,runtime,logs);version=config.get("version","");installRuntime();}
 void configure(String json){config.put("config",json==null?"{}":json);logs.event("info","Configuration saved locally");}
 void installRuntime(){new Thread(()->{try{String manifest=read(new URL(RuntimeManifest.URL));new RuntimeInstaller(context,new RuntimeInstaller.Events(){public void message(String t,String x){logs.event(t,x);}public void progress(String id,long d,long total){try{JSONObject o=new JSONObject();o.put("id",id);o.put("done",d);o.put("total",t);a.emit("runtimeProgress",o.toString());}catch(Exception ignored){}}}).install(RuntimeManifest.parse(manifest));}catch(Exception e){logs.event("error","Runtime manifest rejected: "+e.getMessage());}},"runtime-manifest").start();}
 private String read(URL u)throws Exception{HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","BDS-Control");try(InputStream in=c.getInputStream();ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[]b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);return o.toString("UTF-8");}}
 void listBdsVersions(){new Thread(()->{try{JSONObject root=new JSONObject(read(new URL("https://raw.githubusercontent.com/EndstoneMC/bedrock-server-data/v2/versions.json")));JSONArray names=root.getJSONObject("release").getJSONArray("versions");JSONArray out=new JSONArray();for(int i=0;i<Math.min(names.length(),30);i++){String v=names.getString(i);try{JSONObject m=new JSONObject(read(new URL("https://raw.githubusercontent.com/EndstoneMC/bedrock-server-data/v2/release/"+v+"/metadata.json")));JSONObject linux=m.getJSONObject("binary").getJSONObject("linux");out.put(new JSONObject().put("version",m.optString("version",v)).put("url",linux.getString("url")).put("sha256",linux.getString("sha256")));}catch(Exception ignored){}}a.emit("bdsVersions",out.toString());if(out.length()==0)logs.event("error","BDS version list returned no usable release metadata");}catch(Exception e){logs.event("error","BDS version list unavailable: "+e.getMessage());a.emit("bdsVersions","[]");}} ,"bds-versions").start();}
 private String bdsUrl(String v){return "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-"+v+".zip";}
 void install(String v,String url,String expected){version=v;config.put("version",v);new Thread(()->installArchive(v,url==null||url.isEmpty()?bdsUrl(v):url,expected,null),"bds-install").start();}
 void installLocal(Uri uri){new Thread(()->{try{File zip=new File(root,"local-bds.zip");try(InputStream in=context.getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(zip)){byte[]b=new byte[65536];int n;while((n=in.read(b))>0)out.write(b,0,n);}String expected=new JSONObject(config.get("config","{}")).optString("localSha","");installArchive("local",null,expected,zip);}catch(Exception e){logs.event("error","Local BDS ZIP failed: "+e);}},"bds-local").start();}
 private void installArchive(String v,String url,String expected,File local){try{state="installing";emitState();File zip=local;if(zip==null){zip=new File(root,"bds.zip");DownloadManager.download(url,zip,(d,t)->progress(d,t));}String hash=DownloadManager.sha256(zip);if(expected==null||expected.isEmpty()||!hash.equalsIgnoreCase(expected))throw new SecurityException("BDS SHA-256 mismatch or missing for "+v+": "+hash);File server=new File(root,"server");if(server.exists())delete(server);ArchiveExtractor.zip(zip,server);zip.delete();File bin=new File(server,"bedrock_server");if(!bin.isFile())throw new FileNotFoundException("Archive has no bedrock_server");if(!bin.setExecutable(true,false))throw new IOException("Cannot mark bedrock_server executable");File props=new File(server,"server.properties");if(!props.exists())PropertiesManager.writeDefaults(props,"Bedrock level","19132");logs.event("ready","BDS verified, executable and extracted; SHA-256="+hash);state="stopped";emitState();}catch(Exception e){state="error";logs.event("error",e.toString());emitState();}}
 private void progress(long d,long t){try{JSONObject o=new JSONObject();o.put("done",d);o.put("total",t);a.emit("progress",o.toString());}catch(Exception ignored){}}
 void start(){shuttingDown=false;restarts=0;new Thread(()->{try{File dir=new File(root,"server"),server=new File(dir,"bedrock_server");if(!server.isFile())throw new FileNotFoundException("bedrock_server is not installed; install BDS first and wait for the verified/extracted message");if(!server.canExecute()&&!server.setExecutable(true,false))throw new IOException("bedrock_server is not executable; reinstall BDS");if(!runtime.box64Present()||!runtime.guestLibsPresent())throw new IllegalStateException(runtime.reason());Intent service=new Intent(context,ServerService.class);if(Build.VERSION.SDK_INT>=26)context.startForegroundService(service);else context.startService(service);Map<String,String> env=runtime.env(dir);List<String> cmd=Arrays.asList(runtime.box64().getAbsolutePath(),server.getAbsolutePath());logs.event("info","Starting BDS through Box64");state="starting";emitState();pm.start(cmd,dir,env,(src,line)->logs.line(src,line));started=System.currentTimeMillis();state="running";emitState();maybePlayit();watch();}catch(Exception e){state="error";logs.event("error",e.toString());emitState();}},"bds-start").start();}
 private void maybePlayit(){try{JSONObject o=new JSONObject(config.get("config","{}"));if(o.optBoolean("playitAuto",false))playit.start(o.optString("playitSecret",""));}catch(Exception ignored){}}
 private void watch(){new Thread(()->{try{while(pm.alive()&&!shuttingDown)Thread.sleep(1000);if(!shuttingDown){if(restarts<3){restarts++;logs.event("error","BDS exited; restarting attempt "+restarts+"/3");start();}else{state="error";logs.event("error","BDS exited after 3 restart attempts; manual action required");emitState();}}}catch(InterruptedException ignored){}} ,"bds-watchdog").start();}
 void stop(){shuttingDown=true;pm.stop();playit.stop();context.stopService(new Intent(context,ServerService.class));state="stopped";emitState();}void restart(){restarts=0;stop();try{Thread.sleep(250);}catch(Exception ignored){}start();}void stopAll(){shuttingDown=true;pm.stop();playit.stop();context.stopService(new Intent(context,ServerService.class));}void sendCommand(String c){try{pm.write(c);}catch(Exception e){logs.event("error","stdin: "+e);}}
 void playitStart(String secret){if(secret!=null&&secret.contains(".ply.gg:")){logs.event("error","Playit secret key expected, not a public address. Remove the address and enter the secret key only.");return;}playit.start(secret);}void playitCommand(String line){playit.send(line);}void playitStop(){playit.stop();}
 String systemJson(){return monitor.snapshot();}String statusJson(){try{JSONObject o=new JSONObject();o.put("state",state);o.put("version",version);o.put("alive",pm.alive());o.put("startedAt",started);o.put("playit",new JSONObject(playit.status()));o.put("runtime",new JSONObject(runtime.status()));return o.toString();}catch(Exception e){return "{}";}}private void emitState(){a.emit("state",statusJson());}
 private void delete(File f){if(f.isDirectory()){File[]x=f.listFiles();if(x!=null)for(File y:x)delete(y);}f.delete();}
}
